export const ADD_INSTRACTOR_REQUEST = "ADD_INSTRACTOR_REQUEST";
export const ADD_INSTRACTOR_SUCCESS = "ADD_INSTRACTOR_SUCCESS";
export const ADD_INSTRACTOR_FAILURE = "ADD_INSTRACTOR_FAILURE";
export const ADD_INSTRACTOR_RESET = "ADD_INSTRACTOR_RESET";


export const FETCH_INSTRACTORS_REQUEST = "FETCH_INSTRACTORS_REQUEST";
export const FETCH_INSTRACTORS_SUCCESS = "FETCH_INSTRACTORS_SUCCESS";
export const FETCH_INSTRACTORS_FAILURE = "FETCH_INSTRACTORS_FAILURE";
export const FETCH_INSTRACTORS_RESET = "FETCH_INSTRACTORS_RESET"


export const FETCH_SINGLE_INSTRACTOR_REQUEST = "FETCH_SINGLE_INSTRACTOR_REQUEST";
export const FETCH_SINGLE_INSTRACTOR_SUCCESS = "FETCH_SINGLE_INSTRACTOR_SUCCESS";
export const FETCH_SINGLE_INSTRACTOR_FAILURE = "FETCH_SINGLE_INSTRACTOR_FAILURE";
export const FETCH_SINGLE_INSTRACTOR_RESET = "FETCH_SINGLE_INSTRACTOR_RESET"