export const ADD_COACH_REQUEST = "ADD_COACH_REQUEST";
export const ADD_COACH_SUCCESS = "ADD_COACH_SUCCESS";
export const ADD_COACH_FAILURE = "ADD_COACH_FAILURE";
export const ADD_COACH_RESET = "ADD_COACH_RESET";

export const FETCH_COACHES_REQUEST = "FETCH_COACHES_REQUEST";
export const FETCH_COACHES_SUCCESS = "FETCH_COACHES_SUCCESS";
export const FETCH_COACHES_FAILURE = "FETCH_COACHES_FAILURE";
export const FETCH_COACHES_RESET = "FETCH_COACHES_RESET";


export const FETCH_SINGLE_COACH_REQUEST = "FETCH_SINGLE_COACH_REQUEST";
export const FETCH_SINGLE_COACH_SUCCESS = "FETCH_SINGLE_COACH_SUCCESS";
export const FETCH_SINGLE_COACH_FAILURE = "FETCH_SINGLE_COACH_FAILURE";
export const FETCH_SINGLE_COACH_RESET = "FETCH_SINGLE_COACH_RESET";